# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  dev-peer0.orgtfi.local:
    container_name: dev-peer0.orgtfi.local
    extends:
      file:  base/docker-compose-base.yaml
      service: dev-peer0.orgtfi.local
    # environment:
    #   - CORE_LEDGER_STATE_STATEDATABASE=
    #   - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org1.lychee.com:5984
    extra_hosts:
      - "dev-orderer.local:192.168.33.61"
      - "dev-peer0.orgopensky.local:192.168.33.63"
      - "dev-peer2.orgcandy.local:192.168.33.64"
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - CORE_PEER_CHAINCODELISTENADDRESS=dev-peer0.orgtfi.local:7052
      - GOPATH=/opt/gopath
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=dev-peer0.orgtfi.local:7051
      - CORE_PEER_LOCALMSPID=OrgTFIMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtfi.local/peers/dev-peer0.orgtfi.local/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtfi.local/peers/dev-peer0.orgtfi.local/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtfi.local/peers/dev-peer0.orgtfi.local/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtfi.local/users/Admin@orgtfi.local/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/tfi/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - dev-peer0.orgtfi.local
    extra_hosts:
      - "dev-orderer.local:192.168.33.61"
      - "dev-peer0.orgtfi.local:192.168.33.62"
      - "dev-peer0.orgopensky.local:192.168.33.63"
      - "dev-peer2.orgcandy.local:192.168.33.64"
