NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.orgcandy.local-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.orgcandy.local-cert.pem
    OrganizationalUnitIdentifier: peer
